### ISSUE TITLE
Problem in client-bot communication after a while

### ISSUE THREAD

**Issue by resinas** [isa-group/offline-directline#10]
I've uploaded PPIBot (client, backend and offline-directline) to http://resisa01.us.es/ppibot/ and I've noticed that, at first it works fine, but after a while (around 1 minute, maybe less), the client sends information to the backend, the backend receives and processes it, but the client does not receive the response (only a JSON with an id).

The error is happening with the code that is in the master branch, not the code that is in the ppibot branch (I don't know if the problem was solved at some point)

<img width="1434" alt="Screenshot 2022-01-21 at 14 51 54" src="https://user-images.githubusercontent.com/2464523/150538625-0332602b-5493-45ec-8b38-3f9325de19f7.png">
<img width="1431" alt="Screenshot 2022-01-21 at 14 52 28" src="https://user-images.githubusercontent.com/2464523/150538633-1ff5b4a2-7abe-4ac8-afdc-1ef63abf5f93.png">

**Comment by maribelrb22** [comment]
It seems that in the screenshots you uploaded the client sends an activity (first screenshot) and it receives an immediate response from offline directline with the id of the sent activity. The bot response is expected to be received later, so I am not sure whether this is a bug or not. Does the client stop working or is there an error log anywhere?

**Comment by resinas** [comment]
Ok, so the problem then is that no message is received after the response. The conversation gets stuck at this moment

**Comment by maribelrb22** [comment]
This should be fixed with [this pull request](https://github.com/isa-group/ppibot-frontend/pull/76) in ppibot-frontend

**Comment by bratislav** [comment]
Hello @maribelrb22 @resinas I am experiencing the same problem, but I cannot access this pull request anymore because the ppibot-frontend project has been removed from GitHub. Can you please share the fix from this pull request so I can take a closer look?

Many thanks

**Comment by maribelrb22** [comment]
Hi @bratislav! In our case, the problem was that we were using a reverse proxy (Nginx) to establish a WebSocket connection between the frontend app and the DirectLine server. Nginx closes the connection after 1 min by default, so you'll need to increase this limit (we did increase it to 1 day)

<img width="482" alt="Captura de pantalla 2023-07-24 a las 13 15 49" src="https://github.com/isa-group/offline-directline/assets/62081471/84a1e5bd-2498-4a41-9356-476468749e07">

**Comment by bratislav** [comment]
Many thanks @maribelrb22 !

One thing we noticed is that, no matter if this is set or not, Chrome on mobile phones tends to close the connection immediately after you move onto the other app on your phone...once you come back, you need to wait a little for the directline reconnecting mechanism to take place (just giving some feedback for others, I guess it's irrelevant since the issue has been closed.)

Thanks again
